# Build stage
FROM node:21 AS build-stage
WORKDIR /usr/src/app

# Copy both client and server to the build container
COPY . .

RUN npm install -g npm@10.8.1
# Install client packages
WORKDIR /usr/src/app/client
RUN npm ci

# Install server packages
WORKDIR /usr/src/app/server
RUN npm ci

# Build both client and server according to the build script in package.json
WORKDIR /usr/src/app
RUN npm run build

# Production stage
FROM node:21 AS production-stage

RUN npm install -g npm@10.8.1

WORKDIR /usr/src/app
COPY  --from=build-stage /usr/src/app/server/.env .
COPY  --from=build-stage /usr/src/app/server/build .
COPY  --from=build-stage /usr/src/app/server/package.json .
COPY  --from=build-stage /usr/src/app/server/package-lock.json .
COPY  --from=build-stage /usr/src/app/server/prisma ./prisma
RUN npm ci

EXPOSE ${PORT}
RUN chown -R node /usr/src/app
USER node

RUN npx prisma generate
CMD ["npm", "run", "dstart"]
